name: Krypeia
main: de.minestar.krypteia.core.KrypteiaCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
    krypt:
        description: Super Befehl fuer Krypteia
        usage: /scan